name: typelits-witnesses
version: 0.4.0.0
synopsis: Existential witnesses, singletons, and classes for operations on GHC TypeLits

description: |
  This library contains:

  *   A small specialized subset of the *singletons* library as it pertains to
      `Nat` and `Symbol`, for when you need some simple functionality without
      wanting to invoke the entire *singletons* library.
  *   Operations for manipulating these singletons and `KnownNat` and
      `KnownSymbol` instances, such as addition and multiplication of
      singletons/`KnownNat` instances.
  *   Operations for the comparison of `Nat`s in a way that works well with
      *GHC.TypeLits*'s different comparison systems.  This is helpful for
      bridging together libraries that use different systems; this functionality
      is not yet provided by *singletons*.

category: Data
author: Justin Le
maintainer: justin@jle.im
copyright: (c) Justin Le 2018
license: MIT
homepage: https://github.com/mstksg/typelits-witnesses

git: git://github.com/mstksg/typelits-witnesses.git
tested-with: GHC>=8.2 && <8.8

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wredundant-constraints
- -Werror=incomplete-patterns
- -Wcompat

dependencies:
- base >=4.10 && <5
- dependent-sum

library:
  source-dirs: src
